### ISSUE TITLE
Whether the size of the Batch_size will affect the stability of the training？

### ISSUE THREAD

**Issue by 1120191165** [yz93/LAVT-RIS#10]
I followed Readme to configure the experimental environment. Then, I use GTX 1080Ti with batch_size=2， --nproc_per_node 2.
The first epoch was normal with MIou=50.14, but the MIou in the second epoch  dropped sharply to 0...

**Comment by yz93** [comment]
Hi!

Batch size is critical to obtaining normal results. Generally, one probably doesn't want a batch size smaller than 8 when training any segmentation model. Also generally, one might observe performance benefits with increased batch size, probably up until 64 for segmentation without having to do some optimization hacks.

I recommend trying batch size 16 at the minimum. You can reduce the image resolution to save some GPU memory. Also can try a smaller visual backbone like Swin-small or Swin-tiny.
