### ISSUE TITLE
复现代码问题

### ISSUE THREAD

**Issue by lx1030** [yz93/LAVT-RIS#14]
你好，冒昧打扰一下，有幸读到这篇论文然后现在在复现代码，但是你的代码中很多地方都是针对多gpu进行的，但是我自己的电脑是单GPU的，所以遇到了一些问题，请问这个代码在单GPU上好跑通吗，我只跑通了测试部分，但是训练部分始终没有跑通，希望您能帮忙解答一下，您看到消息后麻烦邮件回复我一下，15666131901@163.com或者vx 15666131901，十分感谢

**Comment by yz93** [comment]
谢谢您对我们工作的关注！应该还是挺简单的，我这里简短回复一下就跳过email了。

是的测试部分就是写的单卡没涉及DDP。因为这个模型需要比较大的batch size才能有效训练，所以单卡如果目的是训练的话实际上不现实，因为装不下。应该最少也需要两个卡，每个48G。不过只需要跑起来的话单卡应该也可以。

（1）我建议先试一下不改代码看torch 的DDP能不能直接单卡跑，我还没试过但感觉没啥理由不行。就这样：CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node 1 --master_port 12345 train.py --model lavt --dataset refcoco --model_id refcoco --batch-size 8 --lr 0.00005 --wd 1e-2 --swin_type base --pretrained_swin_weights ./pretrained_weights/swin_base_patch4_window12_384_22k.pth --epochs 40 --img_size 480 2>&1 | tee ./models/refcoco/output

（2）如果上面的不行或者确定只需要单卡跑的话，那可以在train.py里面把if __name__ == "__main__":下面的utils.init_distributed_mode(args) 删掉，然后把train_sampler换成RandomSampler，然后把模型initialization之后涉及DDP的wrapper代码删掉，就不wrap原模型了类似于以下这些是不需要的
model = torch.nn.SyncBatchNorm.convert_sync_batchnorm(model)
model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[args.local_rank], find_unused_parameters=True)
single_model = model.module，
然后自然地optimizer加参数的时候就直接加原model的参数，然后存weights时候把save_on_master里面的if条件删了就行了，也就是直接的torch.save。涉及DDP的环节应该就是这些了，别的没什么。
