### ISSUE TITLE
About Visualization

### ISSUE THREAD

**Issue by wildwolff** [yz93/LAVT-RIS#18]
appreciate to your contribution!
May I know how to visualize the feature maps in figure.5 of the paper?  By using Grad-CAM of something else?

**Comment by yz93** [comment]
Hi, from what I can recall, it was computed by first taking the absolute value of each element in the feature maps, and then summing along the channel dimension.

Visualization was done through matplotlib.pyplot.imsave using the RdBu_r colormap.

**Comment by lonf69** [comment]
您好 请问可视化的代码可以提供一下嘛
