### ISSUE TITLE
About Semantics-Aware Dynamic Localization 

### ISSUE THREAD

**Issue by PanXiongAdam** [yz93/LAVT-RIS#23]
Hello, Sir. I read your latest article(Semantics-Aware Dynamic Localization and Refinement for Referring Image Segmentation) which is not public code. I don't see you e-mail. So, I contact you  in here. Can you tell me how to acheive the dynamic kernel K? It is very novel idea.

**Comment by yz93** [comment]
Thanks for your interest in our work. It will be a while before we release the code.

Meanwhile, you can refer to https://github.com/PeizeSun/SparseR-CNN/blob/0d2909895fecca7051f0820328345fc61ff0a6e6/projects/SparseRCNN/sparsercnn/head.py#L258 for the implementation of the dynamic kernel.

**Comment by jinx2018** [comment]
> Thanks for your interest in our work. It will be a while before we release the code.
> 
> Meanwhile, you can refer to https://github.com/PeizeSun/SparseR-CNN/blob/0d2909895fecca7051f0820328345fc61ff0a6e6/projects/SparseRCNN/sparsercnn/head.py#L258 for the implementation of the dynamic kernel.

Hope you release the codes of paper `Semantics-Aware Dynamic Localization and Reﬁnement for Referring Image Segmentation` soon

**Comment by PanXiongAdam** [comment]
> Thanks for your interest in our work. It will be a while before we release the code.
> 
> Meanwhile, you can refer to https://github.com/PeizeSun/SparseR-CNN/blob/0d2909895fecca7051f0820328345fc61ff0a6e6/projects/SparseRCNN/sparsercnn/head.py#L258 for the implementation of the dynamic kernel.

@yz93 Hello, Sir. I re-implement the SADLR method, but it decreases the benchmarks of the results when I use the cross-entropy as the supervised loss and re-train the network.  In this, we don't use the multi-class dice. So, can you tell me what caused this?
