### ISSUE TITLE
any training logs?

### ISSUE THREAD

**Issue by runzeer** [yz93/LAVT-RIS#6]
Hi, thanks for your excellent work. If convenient, could you share your training logs when training the RefCOCO+?

**Comment by yz93** [comment]
Sure. We will try and upload a few. Thanks a lot!

**Comment by yz93** [comment]
Hi, if you are still interested, you can take a look at the new training logs. The old ones were cleaned from the cluster that I was using several weeks ago and I've also, unfortunately, lost access to that cluster.
